### ISSUE TITLE
Error when trying to build with gulp

### ISSUE THREAD

**Issue by RCQuest** [ooflorent/js13k-boilerplate#4]
Hey there! Just been trying out this boilerplate but I get a node error when trying to build with gulp:
Error: Cannot find module 'eslint/lib/util'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/js13k-boilerplate-master/node_modules/gulp-eslint/util.js:6:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Any help would be greatly appreciated, thanks in advance!

**Comment by MonsieurLuge** [comment]
Same here, one year later :)

**Comment by danWithABeard** [comment]
Hi @monsieurluge: If you are still having issues with is boilerplate, than you can try the solution presented here: https://github.com/adametry/gulp-eslint/issues/172

The linked thread resolved the issues for me. Hope this helps!

Update the required gulp-eslint version from `^0.1.8` to `4.0.0`, and everything should be work as expected.
